name: Build & Release

on: 
  push:
    branches: [ master, main ]
    paths:
    - '**/*.cs'
    - '**/*.csproj'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Manual Workflow Dispatch Reason'
        required: true
        default: 'Manual Run Test'

jobs:
  build:
    name: Builds the project within the src folder
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v3
    - name: .NET Core SDK Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.X
    
    - name: Dependencies Setup
      run: dotnet restore ./src/

    - name: Build
      run: dotnet publish ./src/ --no-restore --runtime win-x86 -p:PublishSingleFile=true --output ./src/Publish --no-self-contained --configuration Release;

    - name: Archive the Build
      run: 7z a -tzip Release.zip ./src/Publish/*

    - name: Create Release
      uses: actions/create-release@v1
      with:
        tag_name: v1.${{ github.run_number }}
        release_name: Release v1.${{ github.run_number }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Artifacts to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Release.zip
        asset_name: PopupHost_Fix.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}