name: Build & Release

on: 
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag'
        required: true
        default: 'v1.0'

jobs:
  build:
    name: Build Project
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v3
    - name: .NET Core SDK Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.X
    
    - name: Build
      shell: pwsh
      run: .\Build.ps1

    - name: Archive the Build
      run: 7z a -tzip Release.zip ./src/Output/*

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.1.4
      with:
        tag_name: ${{ github.event.inputs.release_tag }}
        release_name: Release ${{ github.event.inputs.release_tag }}
        draft: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Artifacts to Release
      uses: actions/upload-release-asset@v1.0.2
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Release.zip
        asset_name: Tooltip_Fix.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}